### PR TITLE
FIX: Webpacker install

### LINKED ISSUE #18: Webpack dev server doesn't work anymore
After following the installation steps, I cannot start webpack-dev-server anymore.
here's the stacktrace:
```
./bin/webpack-dev-server
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /project/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```

### PR DESCRIPTION
**Pull request by dixpac**
Current webpacker install, was problematic.

Main issue is that current release of webpacker uses Postcss7.
Tailwind 2 expects Postcss8, and that causes a lot of issues.

Tailwind team has published Tailwind 2 compatible Postcss7 [package](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build)

So in order for the generator to work with Rails 6.1 defaults, this PR
deferes to use `tailwindcss@npm:@tailwindcss/postcss7-compat` package.

By, using this package users don't loose anything it is Tailwind 2.

--------------

There is a way to make it work without using the `Postcss7` package by
using latest `rails-webpacker` beta, but I think it is smarter for now
not to use beta releases.

When rails wepbacker publishes latest with `Postcss8` then we can change
the generator.

Shout out to @BakiVernes for helping on this PR.

Fixes #18

### CODE REVIEW

**Comment by miharekar** [comment]
>There is a way to make it work without using the Postcss7 package by
using latest rails-webpacker beta, but I think it is smarter for now
not to use beta releases.

Did you mean postcss8 here?

Is there a upgrade guide of some kind to do it this other way? I followed the README in rails-webpacker, but couldn't get it to work 😅

```
ERROR in ./app/packs/entrypoints/application.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "tailwindcss/base";
```

And I've added all `css-loader mini-css-extract-plugin css-minimizer-webpack-plugin postcss postcss-import postcss-loader` to yarn packages and moved application.css inside `entrypoints`.

Anyway, @dixpac, if you know of any upgrade guide for dummies, I'd like that very much 😅

**Comment by dixpac** [comment]
@miharekar sorry for the late reply 😄 

Here is a demo [repo](https://github.com/dixpac/paket) with PostCSS 8 that works for me.
Don't ask me how it works, only God knows. I tried everything until I get it working 🤣 
Hope it helps!

**Comment by miharekar** [comment]
@dixpac 🙈😂
